name: CodSpeed

on:
  pull_request:
    branches:
      - next
  push:
    branches:
      - next
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Installing deps
        run: pnpm install

      - name: Building
        run: pnpm run build

      - name: Run benchmarks under CodSpeed
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: |
            pnpm --filter solid-signals run bench
            pnpm --filter @solidjs/web run bench
            pnpm --filter @solidjs/web run bench:server
